### ISSUE TITLE
add more trace and debug tools

### ISSUE THREAD

**Issue by lamikr** [lamikr/rocm_sdk_builder#106]
Trying to find out the reason for rx 5700 crash with pytorch-gpu-benchmark lead me to investigate ways to check gpu memory usage/consumption options and want therefore add more tools

- amddbgapi (library required by rocgdb)
- rocgdb (for debugging the rocm apps in gdb style)
- nvtop (memory usage tool that can be run easily on terminal to see gpu utilization and memory usage)
- amd-smi (new tool for tracing amd gpus that is supposed to obsolete the rocm-smi)

**Comment by lamikr** [comment]
todo
- omnitrace
- omniperf

**Comment by jeroen-mostert** [comment]
Ignore all of the above commits, they're not relevant (typo in the commit message).

On a more relevant note, I'm conflicted about the inclusion of something like `nvtop`. This has no dependencies on ROCm at all (just the kernel drivers) and can be installed separately on many distros. If it is to be included "because convenience", it would be nice if we had some clear separation in the `binfo`s between "this needs to be built as part of ROCm/on top of ROCm" vs. "this is there to make your ROCm life easier", because personally I would want to include the former in a build, but not the latter, as my rolling distro is better at keeping up than my local build would be.

**Comment by lamikr** [comment]
Yes, I agree with you in sense that I think there actually starts to be a need for a separation of "core" rocm apps and additional layers. NVTop is an example from binfo file that could be just there separately and one could build it on need basic with something like "./babs.sh -b binfo/nvtop.binfo" or "./babs.sh -b binfo/monitoring_apps.blist"

First one is mentioned here:
https://github.com/lamikr/rocm_sdk_builder/issues/23 

Second one I also thought I already had in issues but could not find it, so created here:
https://github.com/lamikr/rocm_sdk_builder/issues/110

What do you think about this approch?

**Comment by lamikr** [comment]
Latest version builds now ok on ubuntu 24.04, Mageia 9 and Fedora 40.
Install_debs.sh needs to be updated to arch and manjaro linux.

**Comment by jeroen-mostert** [comment]
#23 is useful in general, if your development process is anything like mine you spend quite a bit of time (re)-building individual projects. The separate commands are not difficult, but having it as a built-in would be very nice, especially if it's "half smart" -- see if there already is a git repo, if there isn't, download, otherwise reset it, update it, patch it, wipe the build directory, then build it.

Separate blists is an option, we could also just have a single one if it supports comments -- i.e. a list of optional, curated apps/tools you can uncomment as you please.  There are tons of inference backends and frontends, for example, most people probably don't want to build all of them, but some can be tricky to build/get working for ROCm so it would have real value to add them. (I'm trying to get Aphrodite to work, for example -- this turns out to be not so easy even though it nominally has ROCm support, as some dependencies also need patching.)

One possible challenge is that we can't get too crazy with dependencies because we don't really handle them explicitly, it's just a simple "this needs to build before that" list. Ideally those optional blist apps don't have any dependencies beyond the core ROCm list, and the core ROCm list contains things you are never supposed to disable.

**Comment by lamikr** [comment]
Support for comments is a good point that I did not even think on those lists, they would definitely be useful. And on other things I go pretty much in same way with your thinking.

For the dependencies I have to keep the things as simple as possible. 
1) install_deps.sh for distro specific one
2) backport if distro does not provide something or if there is conflict
3) build order in core binfo list (I did not want to go to the route of each binfo starting to list their own dependencies to another binfo file because their maintenace can be hard)
4) Maybe at some point the binfo-list files could have link to own install_deps.sh type files but that can be thinked later... It's not so important now.

Some more smartness could definitely be added to babs.sh in a way for combining commands.  In the beginning I just
wanted to keep everything separately and in user control as it's makes the testing of these commands simpler and more error proof.

1) I have for example thought should the "./babs.sh -i/-f/-co/ap features all be hidden more advanced commands and something like ./babs.sh -reset would do all those steps.
2) babs.sh -f should automatically detect if some repo is missing and download it. Now that needs to be done as a separate step with ./babs.sh -i
3) if one deletes only the builddir/abc/.result_build
    the babs.sh would only do the build task, not the install and postinstall which follows it.
