### ISSUE TITLE
AOTriton build fails due to missing dependency (libzstd)

### ISSUE THREAD

**Issue by recris** [lamikr/rocm_sdk_builder#146]
Tested on Ubuntu 22.04 (distrobox).

When building aotriton the build fails with a cmake error.

Problem was solved by doing `apt install libzstd-dev` and retrying the build.

The `install_deps.sh` script needs to be updated to include this dependency.

**Comment by jeroen-mostert** [comment]
Probably not, because `zstd` is [built as part of the repo](https://github.com/lamikr/rocm_sdk_builder/blob/master/binfo/core/002_02_zstd_backport.binfo). If the build fails, it's due to this library not being found/linked properly: can you show the error?

Of course if the issue mentioned in that binfo has been resolved we can remove the binfo and revert to distro `zstd`, but then we should probably not do that only for Ubuntu.

**Comment by lamikr** [comment]
Original reason why we build ourself the installation of zstd project worked on all other distros except on the fedora which does not install the zstd cmake files required for the cmake find-command. That's why we are supposed to build and install our own version of zstd under /opt/rocm_sdk and use that.

I can try to check tomorrow if I can reproduce the error on Ubuntu 22.04.

**Comment by lamikr** [comment]
@recris Thank you from the report  and fix suggestion. I pushed that change now to install_deps.sh.

On some other linux distros the zstd-devel was installed automatically due to some other dependencies. Also for some reason the ubuntu cmakes findzstd application was not able to find the zstd version installed under /opt/rocm_sdk_612 directory.
