### ISSUE TITLE
Missing hsa-amd-aqlprofile64 when building rocprofiler

### ISSUE THREAD

**Issue by tvquizphd** [lamikr/rocm_sdk_builder#156]
### What I expect to happen

After successfully running `./babs.sh -i`, I would expect to build the rocm sdk 6.1.2 library using `./babs.sh -b`.  I have selected `gfx1012` when prompted, as my system has a Navi 14 GPU [ **a Radeon Pro W5500** ]. I'm running Ubuntu 22.04.

### What happens instead

I see this error message output when running `./babs.sh -b`:

```
CMake Error at cmake_modules/rocprofiler_env.cmake:83 (find_library):
  Could not find HSA_AMD_AQLPROFILE_LIBRARY using the following names:
  hsa-amd-aqlprofile64
Call Stack (most recent call first):
  CMakeLists.txt:78 (include)
```

Here is the combined standard output / standard error for the `rocprofiler` cmake command.

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_LIBDIR=lib64 -DCMAKE_INSTALL_PREFIX=/opt/rocm_sdk_612 -DCMAKE_PREFIX_PATH=/opt/rocm_sdk_612/lib64/cmake;/opt/rocm_sdk_612/lib/cmake;/opt/rocm_sdk_612/gtest/lib64/cmake -DPROF_API_HEADER_PATH=/home/john/vm/readme-server-owl/reversal/rocm_sdk_builder/src_projects/roctracer/inc/ext -DCMAKE_CXX_COMPILER=/opt/rocm_sdk_612/bin/hipcc -DGPU_TARGETS=gfx1012 /home/john/vm/readme-server-owl/reversal/rocm_sdk_builder/src_projects/rocprofiler
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is Clang 17.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm_sdk_612/bin/hipcc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
----------Build-Type: Release
------------Compiler: /opt/rocm_sdk_612/bin/hipcc
----Compiler-Version: 17.0.0
-------ROCM_ROOT_DIR: /opt/rocm_sdk_612
-----CMAKE_CXX_FLAGS: 
---CMAKE_PREFIX_PATH: /opt/rocm_sdk_612/lib64/cmake;/opt/rocm_sdk_612/lib/cmake;/opt/rocm_sdk_612/gtest/lib64/cmake
---------GPU_TARGETS: gfx1012
CMake Error at cmake_modules/rocprofiler_env.cmake:83 (find_library):
  Could not find HSA_AMD_AQLPROFILE_LIBRARY using the following names:
  hsa-amd-aqlprofile64
Call Stack (most recent call first):
  CMakeLists.txt:78 (include)


-- Configuring incomplete, errors occurred!
See also "/home/john/vm/readme-server-owl/reversal/rocm_sdk_builder/builddir/011_02_rocprofiler/CMakeFiles/CMakeOutput.log".
configure failed: rocprofiler
```

**Comment by lamikr** [comment]
Hi, I think this issue has now been fixed. You should do these commands
to get the latest source code

git pull
./babs.sh -ca
./babs.sh --clean binfo/core/011_02_rocprofiler.binfo
./babs.sh -b

Can you let me know also how it goes with the gfx1012?

I have tried to launch the gfx1012 build this week also on amazon aws by using their G4ad instances which has this gpu.
But I had some difficulties by restoring my old amazon aws account back to active and their support is now working on that... So it seems to take some days before I can test by myself.

**Comment by lamikr** [comment]
Adding little explanation: Original reason for the problem was that I was working for adding the omnitrace to build system and it itself requires the rocprofiler. And by default the rocprofiles usually requires the binary only hsa-amd-aqlprofile library. But in rocm sdk builder we have used to build and patch a little older rocprofiler to avoid the dependency to this library and earlier we did not really lost any known functionality by doing so.

But now that the omnitrace source code is available, we noticed that it really requires the hsa-amd-aqlprofile and it uses some methods from rocprofiler and hsa-runtime for loading and verifying the library. (It's little messy code as there is almost similar hsa-loading code also in omnitrace which anyway ends up calling some functions from rocprofiler)

So for a while there were a never version of rocprofiler included in the rocm sdk builder core build that required the hsa-amd-aqlprofiler binary. It took me a little time to debug and figure this out, as the build worked also without it and also some omnitrace command line tools, while some like omnitrace-avail simply crashed on functionality on xml parsing which first seemed unrelated but was really about omnitracer calling the Translate method from this aqlprofiler.

To make things working while still having some separation to this binary only-module, I ended up doing this anyway little differently on new rocm sdk builder builds:

1) By default the rocm sdk builder core which is build with the "./babs.sh -b" will build the older rocprofiler which does not need the hsa-amd-aqlprofiler.

2) Omnitrace and never rocprofiler can be build optionally (with hsa-amd-aqlprofiler) after the core build with command: "./babs.sh -b binfo/extra/amd_devel_tools.blist" This will then replace the rocprofiler version from core-build with the newer version that will support the loading of hsa-amd-aqlprofile.

Btw, little off topic but there is now 4 different extra-tool lists that can be build separately:

ls -la binfo/extra/*.blist

binfo/extra/ai_tools.blist
binfo/extra/amd_devel_tools.blist
binfo/extra/amd_media_tools.blist
binfo/extra/google_tools.blist

My goal is now to update the documentation on main page to make the documentation to show new features (New apps, babs.sh new functionality, etc...) and then then do the official release.
