### ISSUE TITLE
Compilation on another system

### ISSUE THREAD

**Issue by Bazza-63** [lamikr/rocm_sdk_builder#168]
Is there a way to reuse the compiled ROCm stuff on another? I've tried putting the builddir of my first build into the rocm_sdk_builder folder. The only thing that happens once i run the instalion script is that it completes with out doing anything.

I ask because it'd save a lot of time and hassle. Ideally I'd like to be able to rent a CPU farm and compile it in record time, and then install it onto my computer.

Apologies if this has already been asked before. I look but couldn't find anythinv

**Comment by lamikr** [comment]
Build will search for the .result_* files for each project and if they exist then it will skip that step on the build project. For example the fist project build has these files as a stamps:

ls -la builddir/001_rocm_core/.result*
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_build
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_config
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_install
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_postconfig
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_postinstall
-rw-r--r-- 1 lamikr lamikr 2 Oct  2 03:43 builddir/001_rocm_core/.result_preconfig

And if you remove the builddir/001_rocm_core/.result_install file, and then run the ./babs.sh -b again, it would execute the install step for that that project. If you only want to redo the install step for all projects on another computer, you could then try to delete all of those files with commands like these.

cd builddir
find -name .result_install | xargs -- rm -rf
cd ..
./babs.sh -b

We have added to basb.sh the "--clean" command, but that will then force to do all steps for one project.
    "./babs.sh --clean binfo/core/001_rocm_core.binfo"

And very new command I feel is handy is the 
    "./babs.sh --update"

That command will check which projects has been updated and do the clean command "in background" for those.
So that way you can then do the "./babs.sh -b" and it will only rebuild the changed projects.

**Comment by Bazza-63** [comment]
Worked thank you. I just needed to use an alias as the user names were different.
