### ISSUE TITLE
Issue : Conflicted dependencies being treated as acceptable

### ISSUE THREAD

**Issue by mritunjaymusale** [lamikr/rocm_sdk_builder#25]
Based on the screenshot I think the script should stop the installation if there is an error from the package manager about dependency conflict instead allowing to proceed further
![image](https://github.com/lamikr/rocm_sdk_builder/assets/25117230/7fa3dedf-c5d0-4601-9b65-a53edc1fac1d)

**Comment by lamikr** [comment]
Hi, thanks for the feedback.

The script calls the distributions "package install command" and I think it is its responsibility to handle the conflict situation for example by giving this kind of warning or doing something else.

What we coud add to install_debs.sh is to add some kind of check to the return value of "distro specific install command" and if it returns error, then warn instead of recommending to start the build.

**Comment by lamikr** [comment]
We have now support for some version specific differentation in install_deps.sh.
In addition of generic packages installed for newer ubuntu versions (23.10, 24.04, upcoming Linux Mint) we check if the version is 22.04 or Mint 21 and then install some specific versions of certain packages.
